services:
  frontend:
    build: .
    container_name: community-network-frontend
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./app:/app/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
